# Generated by Django 4.2.25 on 2025-10-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.IntegerField()),
                ("gmail", models.EmailField(max_length=254)),
                ("nombre", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("TURISTA", "Turista"),
                            ("OPERADOR", "Operador"),
                            ("ADMIN", "Admin"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
