# Generated by Django 4.2.25 on 2025-11-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("dni", models.CharField(blank=True, max_length=10)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="perfiles/"),
                ),
            ],
        ),
    ]
