# Generated by Django 4.2.25 on 2025-11-05 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("usuarios", "0002_perfil"),
        ("colectivos", "0005_alter_colectivo_operador"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Usuario",
        ),
        migrations.AddField(
            model_name="perfil",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
