# Generated by Django 4.2.25 on 2025-11-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0003_delete_usuario_perfil_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="rol",
            field=models.CharField(
                choices=[
                    ("OPERADOR", "Operador"),
                    ("ADMINISTRADOR", "administrador"),
                    ("TURISTA", "Turista"),
                ],
                default="Turista",
                max_length=20,
            ),
        ),
    ]
