# Generated by Django 4.2.25 on 2025-11-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0004_perfil_rol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="rol",
            field=models.CharField(
                choices=[
                    ("OPERADOR", "Operador"),
                    ("ADMINISTRADOR", "administrador"),
                    ("TURISTA", "Turista"),
                ],
                default="TURISTA",
                max_length=20,
            ),
        ),
    ]
