# Generated by Django 4.2.25 on 2025-10-15 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Itinerario",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PuntoDestacado",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.CharField(max_length=200)),
                ("imagen", models.ImageField(upload_to="")),
                (
                    "itinerario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="itinerarios.itinerario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Parada",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("ubicacion", models.CharField(max_length=50)),
                ("descripcion", models.CharField(max_length=200)),
                (
                    "itinerario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="itinerarios.itinerario",
                    ),
                ),
            ],
        ),
    ]
