# Generated by Django 4.2.25 on 2025-11-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itinerarios", "0002_puntodestacado_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itinerario",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="parada",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="puntodestacado",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
