# Generated by Django 4.2.25 on 2025-11-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itinerarios", "0003_alter_itinerario_id_alter_parada_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itinerario",
            name="imagen",
            field=models.ImageField(
                blank=True, default="images/default.png", null=True, upload_to="images/"
            ),
        ),
    ]
