# Generated by Django 4.2.25 on 2025-10-15 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("colectivos", "0001_initial"),
        ("itinerarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Circuito",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("horario", models.TimeField()),
                (
                    "colectivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="colectivos.colectivo",
                    ),
                ),
                (
                    "itinerario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="itinerarios.itinerario",
                    ),
                ),
            ],
        ),
    ]
