# Generated by Django 4.2.25 on 2025-11-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recorridos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="circuito",
            name="estado",
            field=models.CharField(
                choices=[
                    ("ELIMINADO", "Eliminado"),
                    ("ACTIVO", "Activo"),
                    ("BAJA", "Baja"),
                ],
                default="ACTIVO",
                max_length=20,
            ),
        ),
    ]
