# Generated by Django 4.2.25 on 2025-11-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recorridos", "0002_circuito_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circuito",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
