# Generated by Django 4.2.25 on 2025-11-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recorridos", "0003_alter_circuito_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="circuito",
            name="destino",
            field=models.CharField(default="sin destino", max_length=50),
        ),
        migrations.AddField(
            model_name="circuito",
            name="origen",
            field=models.CharField(default="sin origen", max_length=50),
        ),
    ]
