# Generated by Django 4.2.25 on 2025-11-04 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recorridos", "0004_circuito_destino_circuito_origen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="circuito",
            name="colectivo",
        ),
    ]
