# Generated by Django 4.2.25 on 2025-11-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recorridos", "0005_remove_circuito_colectivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circuito",
            name="horario",
            field=models.DateTimeField(),
        ),
    ]
