# Generated by Django 4.2.25 on 2025-11-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colectivos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="colectivo",
            name="descripcion",
            field=models.TextField(default="sin descripcion", max_length=200),
        ),
        migrations.AddField(
            model_name="colectivo",
            name="estado",
            field=models.CharField(
                choices=[
                    ("ELIMINADO", "Eliminado"),
                    ("ACTIVO", "Activo"),
                    ("BAJA", "Baja"),
                ],
                default="ACTIVO",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="colectivo",
            name="nombre",
            field=models.CharField(default="sin nombre", max_length=20),
        ),
    ]
