# Generated by Django 4.2.25 on 2025-11-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colectivos", "0002_colectivo_descripcion_colectivo_estado_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="colectivo",
            old_name="cantAsientos",
            new_name="cant_asientos",
        ),
        migrations.AddField(
            model_name="colectivo",
            name="cant_ocupados",
            field=models.IntegerField(default=0),
        ),
    ]
