# Generated by Django 4.2.25 on 2025-11-04 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recorridos", "0005_remove_circuito_colectivo"),
        ("colectivos", "0003_rename_cantasientos_colectivo_cant_asientos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="colectivo",
            name="circuito",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recorridos.circuito",
            ),
        ),
    ]
