# Generated by Django 4.2.25 on 2025-11-05 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0002_perfil"),
        ("colectivos", "0004_colectivo_circuito"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colectivo",
            name="operador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="usuarios.perfil"
            ),
        ),
    ]
