# Generated by Django 4.2.25 on 2025-10-15 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("recorridos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("fecha", models.DateField()),
                ("puntoPartida", models.CharField(max_length=100)),
                ("cantCupos", models.IntegerField()),
                (
                    "circuito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recorridos.circuito",
                    ),
                ),
            ],
        ),
    ]
