# Generated by Django 4.2.25 on 2025-11-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
