# Generated by Django 4.2.25 on 2025-11-04 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("colectivos", "0002_colectivo_descripcion_colectivo_estado_and_more"),
        ("reservas", "0002_alter_reserva_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="colectivo",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="colectivos.colectivo",
            ),
        ),
    ]
